pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    parameters {
        string(name: 'Jenkins', defaultValue: 'jenkins', description: 'Please provide the name')
        choice(name: 'Env', choices: ['dev', 'QA', 'PROD'], description: 'Please provide the ENV')
        text(name: 'Version', defaultValue: '1.0.0', description: 'Enter the Version')
    }
    stages {
        stage('Git Checkout') { 
            steps {
                // Using the native Jenkins Git step
                git url: 'https://github.com/Tejag142/JS-Workspace.git', branch: 'master' 
            }
        }
        stage('Build') { 
            steps {
                dir('projects/pop-balloons') {
                    // Wrapping the bash command in an 'sh' step
                    sh 'docker build -t popballoon:${params.Version} .' 
                }
            }
        }
    }
}