pipeline {
    agent any
    options {
        timeout( time: 10, units: 'MINUTES' )
        disableConcurrentBuilds()
    }
    parameters{
        string(name: 'Jenkins', defaultValue: 'jenkins', description: 'Please provide the name')
        choice(name: 'Env', choices: ['dev', 'QA', 'PROD'], description: 'Please provide the ENV')
        text(name: 'Version', defaultValue: '1.0.0', description: 'Enter the Version')
    }
    stages {
        stage ('Git Checkout')
        steps {
            dir ('projects/pop-balloons')
            git clone https://github.com/Tejag142/JS-Workspace
        }
    }
        
}